name: Run Integration Tests

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cdk:
    name: Chaos Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Lambdas
        run: cd lambda-functions && mvn clean package shade:shade

      - name: Spin up LocalStack
        run: |
          docker-compose up -d
          sleep 100
        env: 
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Run Integration Tests
        run: |
          pip3 install boto3 pytest
          pytest
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
